Add pdfbox-io as a orbit dependency to exclude sun.misc import
wso2/orbit pull request #1072
Opened 2024-02-08 06:31 UTC by DinithHerath

## Purpose

- For the dependency upgrade process of pdfbox to 3.0.1, there is an extra import needed for pdfbox-io dependency.
- As per the https://mvnrepository.com/artifact/org.apache.pdfbox/pdfbox-io this is a new requirement came for 3.x versions.
- In the pdfbox-io `MANIFEST.MF`, there is an additional import for sun-misc which is not been even used in the code itself.
- This gives an OSGi error as the sun.misc is not currently exported from any of the packages in the pack.
- Related to https://github.com/wso2/carbon-apimgt/pull/12251

## Implementation
- Removed the sun.misc dependency by orbiting the pdfbox-io

2024-02-13 05:12 UTC, GihanAyesh requested changes

2024-02-13 05:12 UTC, GihanAyesh commented on pdfbox-io/3.0.1.wso2v1/pom.xml
> + ~ Copyright (c) 2015, WSO2 Inc. (http://wso2.com) All Rights Reserved.
Update the license header

2024-03-04 07:04 UTC, lasanthaS approved these changes

2024-03-04 07:07 UTC, GihanAyesh approved these changes

2024-03-04 07:09 UTC, merged